services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - harcama-takip-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://harcama-takip-db:3306/expenses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - harcama-takip-net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - m2_cache:/root/.m2
    restart: unless-stopped
    networks:
      - harcama-takip-net

  harcama-takip-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: expenses
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
      MYSQL_ROOT_PASSWORD: postgres
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - harcama-takip-net

volumes:
  db_data: {}
  jenkins_home:
    driver: local
  m2_cache:
    driver: local

networks:
  harcama-takip-net: