version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - m2_cache:/root/.m2

    depends_on:
      - harcama-takip-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://harcama-takip-db:5432/expenses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - harcama-takip-net

  harcama-takip-db:
    image: postgres:15
    container_name: harcama-takip-db
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - harcama-takip-net

volumes:
  db_data: {}
  jenkins_home:
    driver: local
  m2_cache:
    driver: local

networks:
  harcama-takip-net:
